apiVersion: v1
#appVersion: "^0.3.1"
#kubeVersion: "^v1.16"
description: Cluster image security suite
name: klustair
version: 0.3.2
keywords:
  - security
  - vulnerability
  - audit
home: https://www.klustair.com
sources:
  - https://github.com/klustair/klustair-frontend
  - https://github.com/klustair/klustair
  - https://github.com/klustair/klustair-helm
icon: https://raw.githubusercontent.com/klustair/klustair-helm/main/klustair/static/klustair.png
annotations:
  artifacthub.io/changes: |
    - Frontend, added LDAP user authentication
    - Helm, upgrade PostgreSQL version 
    - Frontend, Laravel upgrade
    - Runner, Kubeaudit upgraded
  artifacthub.io/images: |
    - name: klustair
      image: klustair/klustair:v0.3.2
    - name: klustair-apache
      image: klustair/klustair-frontend:v0.3.2-apache
      whitelisted: true
    - name: klustair-nginx
      image: klustair/klustair-frontend:v0.3.2-nginx
    - name: klustair-php-fpm
      image: klustair/klustair-frontend:v0.3.2-php-fpm
    - name: postgresql
      image: postgres:12-alpine
      whitelisted: true