apiVersion: v1
#appVersion: "^0.3.1"
#kubeVersion: "^v1.16"
description: Cluster image security suite
name: klustair
version: 0.3.2
keywords:
  - security
  - vulnerability
  - audit
home: https://www.klustair.com
sources:
  - https://github.com/klustair/klustair-frontend
  - https://github.com/klustair/klustair
  - https://github.com/klustair/klustair-helm
icon: https://raw.githubusercontent.com/klustair/klustair-helm/main/klustair/static/klustair.png
annotations:
  artifacthub.io/changes: |
    - Frontend, composer and npm upgrade 
    - Runner, Kubeaudit upgraded to version to 0.14.0
    - Runner, Trivy upgraded to version 0.17.2
  artifacthub.io/images: |
    - name: klustair
      image: klustair/klustair:v0.3.3
    - name: klustair-apache
      image: klustair/klustair-frontend:v0.3.3-apache
      whitelisted: true
    - name: klustair-nginx
      image: klustair/klustair-frontend:v0.3.3-nginx
    - name: klustair-php-fpm
      image: klustair/klustair-frontend:v0.3.3-php-fpm
    - name: postgresql
      image: postgres:12-alpine
      whitelisted: true