apiVersion: v1
#appVersion: "^0.2.4"
#kubeVersion: "^v1.16"
description: Cluster image security suite
name: klustair
version: 0.3.0
keywords:
  - security
  - vulnerability
  - audit
home: https://www.klustair.com
sources:
  - https://github.com/klustair/klustair-frontend
  - https://github.com/klustair/klustair
  - https://github.com/klustair/klustair-helm
icon: https://raw.githubusercontent.com/klustair/klustair-helm/main/klustair/static/klustair.png
annotations:
  artifacthub.io/changes: |
    - Runner, collect report data
  artifacthub.io/images: |
    - name: klustair
      image: klustair/klustair:v0.3.0
    - name: klustair-apache
      image: klustair/klustair-frontend:v0.3.0-apache
      whitelisted: true
    - name: klustair-nginx
      image: klustair/klustair-frontend:v0.3.0-nginx
    - name: klustair-php-fpm
      image: klustair/klustair-frontend:v0.3.0-php-fpm
    - name: postgresql
      image: postgres:12-alpine
      whitelisted: true