apiVersion: v1
#appVersion: "^0.2.4"
#kubeVersion: "^v1.16"
description: Cluster image security suite
name: klustair
version: 0.2.7
keywords:
  - security
  - vulnerability
  - audit
home: https://www.klustair.com
sources:
  - https://github.com/klustair/klustair-frontend
  - https://github.com/klustair/klustair
  - https://github.com/klustair/klustair-helm
icon: https://raw.githubusercontent.com/klustair/klustair-helm/main/klustair/static/klustair.png
annotations:
  artifacthub.io/changes: |
    - Helm: use alpine images to reduce vulnerabilities
  artifacthub.io/images: |
    - name: klustair
      image: klustair/klustair:v0.2.7
    - name: klustair-frontend
      image: klustair/klustair-frontend:v0.2.7
    - name: postgresql
      image: postgres:12-alpine