apiVersion: v1
version: 0.2.5
appVersion: ^0.2.4
kubeVersion: ^1.16.0
description: Kluster image vulnerability suite
name: klustair
keywords:
  - security
  - vulnerability
  - audit
home: https://www.klustair.com
sources:
  - https://github.com/klustair/klustair-frontend
  - https://github.com/klustair/klustair
  - https://github.com/klustair/klustair-helm
icon: https://raw.githubusercontent.com/klustair/klustair-helm/main/klustair/static/klustair.png