apiVersion: v2
appVersion: "0.5.0"
kubeVersion: "^v1.16"
description: Klustair is a security toolkit that provides a set of tools to detect and report on security vulnerabilities in Kubernetes clusters.
name: klustair
version: 0.5.0
keywords:
  - security
  - vulnerability
  - audit
home: https://www.klustair.com
sources:
  - https://github.com/klustair/klustair-frontend
  - https://github.com/klustair/klustair
  - https://github.com/klustair/klustair-helm
icon: https://raw.githubusercontent.com/klustair/klustair-helm/main/klustair/static/klustair.png
dependencies:
  - name: postgresql
    version: "10.8"
    repository: "https://charts.bitnami.com/bitnami"
annotations:
  category: Security
  artifacthub.io/changes: |
    - Frontend, Changed sorting on overview
    - Frontend, Show pod age
    - Frontend, Show image age
    - Helm, Removed PVC for frontend

  artifacthub.io/images: |
    - name: klustair
      image: klustair/klustair:v0.5.0
    - name: klustair-apache
      image: klustair/klustair-frontend:v0.5.0-apache
      whitelisted: true
    - name: klustair-nginx
      image: klustair/klustair-frontend:v0.5.0-nginx
    - name: klustair-php-fpm
      image: klustair/klustair-frontend:v0.5.0-php-fpm
    - name: postgresql
      image: postgres:12-alpine
      whitelisted: true