kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "klustair.fullname" . }}-storage
  labels:
{{ include "klustair.labels" . | indent 4 }}
spec:
  storageClassName: {{ .Values.klustairfrontend.pvc.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.klustairfrontend.pvc.size }}