kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "klustair.fullname" . }}-storage
  labels:
{{ include "klustair.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi