{{- if .Values.klustairJob.keeparunner -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "klustair.fullname" . }}-runner
  labels:
{{ include "klustair.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "klustair.name" . }}-runner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "klustair.name" . }}-runner
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      {{- if .Values.klustairJob.serviceAccount.create }}
      serviceAccountName: {{ template "klustair.jobServiceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-runner
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["tail", "-f", "/dev/null"]
          env:
            - name: KUBECONFIG
              value: /etc/klustair/kube.config
            - name: KLUSTAIR_TRIVYCREDENTIALSPATH
              value: "/etc/klustair/repo-credentials.json"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/klustair/gcloud-credentials.json"
            - name: TRIVY_TIMEOUT
              value: {{ .Values.trivy.timeout | quote}}
            {{ if .Values.klustairJob.apiHost }}
            - name: KLUSTAIR_APIHOST
              value: {{ .Values.klustairJob.apiHost | quote}}
            {{ else }}
            - name: KLUSTAIR_APIHOST
              value: "http://{{ include "klustair.fullname" . }}-frontend"
            {{ end -}}
            - name: KLUSTAIR_APITOKEN
              value: {{ .Values.klustairfrontend.apiToken | default "not_set" | quote}}
            {{ if .Values.klustair.configKey }}
            - name: KLUSTAIR_CONFIGKEY
              value: {{ .Values.klustairJob.configKey | quote}}
            {{ end -}}
            - name: KLUSTAIR_LIMITDATE
              value: {{ .Values.klustairJob.limitDate | default "false" | quote}}
            - name: KLUSTAIR_LIMITDATE
              value: {{ .Values.klustairJob.limitNR | default "false" | quote}}
          volumeMounts:
            - name: configs
              mountPath: "/etc/klustair"
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: configs
          secret:
              secretName: {{ include "klustair.fullname" . }}-configs
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}