{{- if .Values.klustairJob.keeparunner -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "klustair.fullname" . }}-runner
  labels:
{{ include "klustair.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "klustair.name" . }}-runner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "klustair.name" . }}-runner
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- if .Values.klustairJob.podLabels }}
        {{- toYaml .Values.klustairJob.podLabels | nindent 8 }}
        {{- end }}        
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      {{- if .Values.klustairJob.serviceAccount.create }}
      serviceAccountName: {{ template "klustair.jobServiceAccountName" . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-runner
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: false
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["tail", "-f", "/dev/null"]
          env:
            - name: KUBECONFIG
              value: /etc/klustair/kube.config
            - name: KLUSTAIR_TRIVYCREDENTIALSPATH
              value: "/etc/klustair/repo-credentials.json"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/klustair/gcloud-credentials.json"
            - name: TRIVY_TIMEOUT
              value: {{ .Values.trivy.timeout | quote}}
            - name: KLUSTAIR_APITOKEN
              value: {{ .Values.klustairfrontend.apiToken | default "not_set" | quote}}
            - name: KLUSTAIR_KUBEAUDIT
              value: {{ .Values.klustairJob.limitDate | default "all" | quote}}
            {{ if .Values.klustairJob.apiHost }}
            - name: KLUSTAIR_APIHOST
              value: {{ .Values.klustairJob.apiHost | quote}}
            {{ else }}
            - name: KLUSTAIR_APIHOST
              value: "http://{{ include "klustair.fullname" . }}-frontend"
            {{ end -}}
            {{ if .Values.klustairJob.configKey }}
            - name: KLUSTAIR_CONFIGKEY
              value: {{ .Values.klustairJob.configKey | quote}}
            {{ end -}}
            {{ if .Values.klustairJob.namespaces }}
            - name: KLUSTAIR_NAMESPACES
              value: {{ .Values.klustairJob.namespaces | quote}}
            {{ end -}}
            {{ if .Values.klustairJob.namespaceblacklist }}
            - name: KLUSTAIR_NAMESPACEBLACKLIST
              value: {{ .Values.klustairJob.namespaceblacklist | quote}}
            {{ end -}}
            {{ if .Values.klustairJob.limitDate }}
            - name: KLUSTAIR_LIMITDATE
              value: {{ .Values.klustairJob.limitDate | quote}}
            {{ end -}}
            {{ if .Values.klustairJob.limitNR }}
            - name: KLUSTAIR_LIMITDATE
              value: {{ .Values.klustairJob.limitNR | quote}}
            {{ end }}
          volumeMounts:
            - name: configs
              mountPath: "/etc/klustair"
              readOnly: true
          resources:
            {{- toYaml .Values.klustairJob.resources | nindent 12 }}
      volumes:
        - name: configs
          secret:
              secretName: {{ include "klustair.fullname" . }}-configs
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}