apiVersion: v1
kind: Secret
metadata:
  name: {{ include "klustair.fullname" . }}-configs
  labels:
{{ include "klustair.labels" . | indent 4 }}
#  annotations:
#    "helm.sh/hook": "pre-install"
#    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  {{ if .Values.klustair.kubeconfig }}
  "kube.config": {{ .Values.klustair.kubeconfig | b64enc | quote }}
  {{ end -}}
  {{ if .Values.trivy.repoCredentials }}
  "repo-credentials.json": {{ .Values.trivy.repoCredentials | b64enc | quote }}
  {{ end -}}
  {{ if .Values.klustair.gcloudCredentials }}
  "gcloud-credentials.json": {{ .Values.klustair.gcloudCredentials | b64enc | quote }}
  {{ end -}}
