{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "klustair.serviceAccountName" . }}
  labels:
{{ include "klustair.labels" . | indent 4 }}
{{- end -}}
