{{- if index .Values "klustair-runner" "enabled" -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scanner
spec:
  schedule: {{ index .Values "klustair-runner" "schedule" }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: klustair-runner
            image: {{ .Values.klustair.image }}:{{ .Values.klustair.tag }}
            imagePullPolicy: {{ .Values.pullPolicy }}
            command: ["runner.py", "--verbose", , "-t", "--namespacesblacklist", {{ index .Values "klustair-runner" "namespaceblacklist" }}]
            env:
              - name: ANCHORE_CLI_URL
                value: {{ .Values.anchore.cliURL }}
              - name: ANCHORE_CLI_USER
                value: {{ .Values.anchore.cliUser }}
              - name: ANCHORE_CLI_PASS
                value: {{ .Values.anchore.cliURL }}
              - name: KUBECONFIG
                value: /configs/kube.config
              - name: DB_HOST
                value: {{ .Release.Name }}-postgresql
              - name: DB_DATABASE
                value: {{ .Values.postgres.postgresqlDatabase | quote}}
              - name: DB_USERNAME
                value: {{ .Values.postgres.postgresqlUsername | quote}}
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Release.Name }}-postgresql
                    key: postgresql-password
            volumeMounts:
              - name: kubeconfig
                mountPath: "/configs"
                readOnly: true
          restartPolicy: OnFailure
          volumes:
          - name: kubeconfig
            secret:
                secretName: {{ .Release.Name }}-kubeconfig
{{- end }}
