{{- if .Values.klustairJob.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "klustair.fullname" . }}-job
  labels:
{{ include "klustair.labels" . | indent 4 }}
spec:
  schedule: {{ .Values.klustairJob.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}-runnerjob
            securityContext:
              {{- toYaml .Values.securityContext | nindent 12 }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["runner.py", "--verbose", , "-t", "--namespacesblacklist", {{ .Values.klustairJob.namespaceblacklist }}]
            env:
              - name: ANCHORE_CLI_URL
                value: {{ .Values.anchore.cliURL }}
              - name: ANCHORE_CLI_USER
                value: {{ .Values.anchore.cliUser }}
              - name: ANCHORE_CLI_PASS
                value: {{ .Values.anchore.cliURL }}
              - name: KUBECONFIG
                value: /configs/kube.config
              - name: DB_HOST
                value: {{ .Release.Name }}-postgresql
              - name: DB_DATABASE
                value: {{ .Values.postgresql.postgresqlDatabase | quote}}
              - name: DB_USERNAME
                value: {{ .Values.postgresql.postgresqlUsername | quote}}
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Release.Name }}-postgresql
                    key: postgresql-password
            volumeMounts:
              - name: kubeconfig
                mountPath: "/configs"
                readOnly: true
            resources:
              {{- toYaml .Values.resources | nindent 12 }}
          volumes:
            - name: kubeconfig
              secret:
                  secretName: {{ include "klustair.fullname" . }}-kubeconfig
          restartPolicy: OnFailure
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
        {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
