apiVersion: apps/v1
kind: Deployment
metadata:
  name: klustair  
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klustair
  template:
    metadata:
      labels:
        app: klustair
    spec:
      containers:
        - name: klustair-runner
          image: {{ .Values.klustair.image }}:{{ .Values.klustair.tag }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          command: ["tail", "-f", "/dev/null"]
          env:
            - name: DOCKER_USER
              value: {{ .Values.klustair.dockerUser }}
            - name: DOCKER_PASS
              value: {{ .Values.klustair.dockerPass }}
            - name: ANCHORE_CLI_USER
              value: "admin"
            - name: ANCHORE_CLI_PASS
              value: {{ index .Values "anchore-engine" "anchoreGlobal" "defaultAdminPassword" }}
            - name: ANCHORE_CLI_URL
              value: {{ .Values.klustair.AnchoreCliUrl }}
            - name: KUBECONFIG
              value: /configs/kube.config
            - name: DB_HOST
              value: {{ .Release.Name }}-postgresql
            - name: DB_DATABASE
              value: {{ index .Values "anchore-engine" "postgresql" "postgresDatabase" }}
            - name: DB_USERNAME
              value: {{ index .Values "anchore-engine" "postgresql" "postgresUser" }}
            - name: DB_PASSWORD
              value: {{ index .Values "anchore-engine" "postgresql" "postgresPassword" }}
          volumeMounts:
            - name: kubeconfig
              mountPath: "/configs"
              readOnly: true
      volumes:
      - name: kubeconfig
        secret:
            secretName: {{ .Release.Name }}-kubeconfig