apiVersion: apps/v1
kind: Deployment
metadata:
  name: klustair  
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klustair
  template:
    metadata:
      labels:
        app: klustair
    spec:
      containers:
        - name: klustair-runner
          image: {{ .Values.klustair.image }}:{{ .Values.klustair.tag }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          command: ["tail", "-f", "/dev/null"]
          env:
            - name: ANCHORE_CLI_URL
              value: {{ .Values.anchore.cliURL }}
            - name: ANCHORE_CLI_USER
              value: {{ .Values.anchore.cliUser }}
            - name: ANCHORE_CLI_PASS
              value: {{ .Values.anchore.cliURL }}
            - name: KUBECONFIG
              value: /configs/kube.config
            - name: DB_HOST
              value: {{ .Release.Name }}-postgresql
            - name: DB_DATABASE
              value: {{ .Values.postgres.postgresqlDatabase | quote}}
            - name: DB_USERNAME
              value: {{ .Values.postgres.postgresqlUsername | quote}}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: postgresql-password
          volumeMounts:
            - name: kubeconfig
              mountPath: "/configs"
              readOnly: true
      volumes:
      - name: kubeconfig
        secret:
            secretName: {{ .Release.Name }}-kubeconfig