apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "klustair.fullname" . }}
  labels:
{{ include "klustair.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "klustair.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "klustair.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "klustair.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-runner
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["tail", "-f", "/dev/null"]
          env:
            - name: ANCHORE_CLI_URL
              value: {{ .Values.anchore.cliURL }}
            - name: ANCHORE_CLI_USER
              value: {{ .Values.anchore.cliUser }}
            - name: ANCHORE_CLI_PASS
              value: {{ .Values.anchore.cliURL }}
            - name: KUBECONFIG
              value: /configs/kube.config
            - name: DB_HOST
              value: {{ .Release.Name }}-postgresql
            - name: DB_DATABASE
              value: {{ .Values.postgres.postgresqlDatabase | quote}}
            - name: DB_USERNAME
              value: {{ .Values.postgres.postgresqlUsername | quote}}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: postgresql-password
          volumeMounts:
            - name: kubeconfig
              mountPath: "/configs"
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: kubeconfig
          secret:
              secretName: {{ include "klustair.fullname" . }}-kubeconfig
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
