apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "klustair.fullname" . }}-frontend
  labels:
{{ include "klustair.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "klustair.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "klustair.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "klustair.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-dbinit
          image: "{{ .Values.image.repositoryFrontend }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["php", "artisan", "migrate"]
          env:
            - name: LOG_CHANNEL
              value: "stderr"
            - name: APP_NAME
              value: "klustair"
            - name: APP_ENV
              value: "local"
            - name: DB_CONNECTION
              value: pgsql
            - name: DB_HOST
              value: {{ .Release.Name }}-postgresql
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: {{ .Values.postgresql.postgresqlDatabase | quote}}
            - name: DB_USERNAME
              value: {{ .Values.postgresql.postgresqlUsername | quote}}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: postgresql-password
            - name: DB_AUTHENTICATION_DATABASE
              value: {{ .Values.postgresql.postgresqlDatabase | quote}}
      containers:
        - name: {{ .Chart.Name }}-frontend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repositoryFrontend }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOG_CHANNEL
              value: "stderr"
            - name: APACHE_DOCUMENT_ROOT
              value: {{ .Values.klustairfrontend.apachedocumentroot | quote}}
            - name: APP_NAME
              value: "klustair"
            - name: APP_ENV
              value: "local"
            - name: APP_KEY
              value: {{ .Values.klustairfrontend.appkey | quote}}
            - name: APP_DEBUG
              value: "true"
            - name: APP_URL
              value: "http://{{ .Values.klustairfrontend.url }}"
            - name: DB_CONNECTION
              value: pgsql
            - name: DB_HOST
              value: {{ .Release.Name }}-postgresql
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: {{ .Values.postgresql.postgresqlDatabase | quote}}
            - name: DB_USERNAME
              value: {{ .Values.postgresql.postgresqlUsername | quote}}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: postgresql-password
            - name: DB_AUTHENTICATION_DATABASE
              value: {{ .Values.postgresql.postgresqlDatabase | quote}}
            - name: BROADCAST_DRIVER
              value: "log"
            - name: CACHE_DRIVER
              value: "file"
            - name: QUEUE_CONNECTION
              value: "sync"
            - name: SESSION_DRIVER
              value: "file"
            - name: SESSION_LIFETIME
              value: "120"
            - name: ANCHORE_API_URL
              value: {{ .Values.anchore.cliURL | quote}}
            - name: ANCHORE_CLI_USER
              value: {{ .Values.anchore.cliUser | quote}}
            - name: ANCHORE_CLI_PASS
              value: {{ .Values.anchore.cliPass | quote}}
            - name: TRIVY_AUTH_URL
              value: {{ .Values.trivy.authUrl | quote}}
            - name: TRIVY_USERNAME
              value: {{ .Values.trivy.authUser | quote}}
            - name: TRIVY_PASSWORD
              value: {{ .Values.trivy.authPass | quote}}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#              httpHeaders:
#              - name: Host
#                value: {{ .Values.klustairfrontend.url }}
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
#              httpHeaders:
#              - name: Host
#                value: {{ .Values.klustairfrontend.url }}

          volumeMounts:
            - mountPath: /var/www/storage
              name: storage
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ template "klustair.fullname" . }}-storage
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
