apiVersion: v1
kind: Secret
metadata:
  name: {{ include "klustair.fullname" . }}-trivy
  labels:
{{ include "klustair.labels" . | indent 4 }}
#  annotations:
#    "helm.sh/hook": "pre-install"
#    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  "trivy-repo-password": {{ .Values.trivy.authPass | b64enc | quote }}